// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyLeasing.API.Models;

#nullable disable

namespace PropertyLeasing.API.Migrations.PropertyLeasingDb
{
    [DbContext(typeof(PropertyLeasingDbContext))]
    [Migration("20260506195811_AddLeaseLogs")]
    partial class AddLeaseLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyLeasing.API.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("DocumentId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UserId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LeaseEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LeaseStartDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SecurityDeposit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeaseId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Lease");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RequestedEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ApplicationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaseApplication");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseApplicationLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByUserID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("LeaseApplicationLog");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByUserID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeaseLog");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedStaffID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("TenantUserId")
                        .HasColumnType("int")
                        .HasColumnName("TenantUserID");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("RequestId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("TenantUserId");

                    b.HasIndex("UnitId");

                    b.ToTable("MaintenanceRequest");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByUserID");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.HasKey("HistoryId");

                    b.HasIndex("RequestId");

                    b.ToTable("MaintenanceStatusHistory");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LeaseId");

                    b.ToTable("PaymentRecord");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PropertyId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Amenities")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AvailabilityStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MonthlyRent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.Property<double?>("Sizesqm")
                        .HasColumnType("float");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvailabilityStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Document", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.LeaseApplication", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK_Document_Application");

                    b.HasOne("PropertyLeasing.API.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Document_User");

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Feedback", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Unit");

                    b.HasOne("PropertyLeasing.API.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_User");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.LeaseApplication", "Application")
                        .WithMany("Leases")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lease_LeaseApplication");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseApplication", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("LeaseApplications")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseApplication_Unit");

                    b.HasOne("PropertyLeasing.API.Models.User", "User")
                        .WithMany("LeaseApplications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseApplication_User");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseApplicationLog", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.LeaseApplication", "Application")
                        .WithMany("ApplicationLogs")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseApplicationLog_Application");

                    b.HasOne("PropertyLeasing.API.Models.User", "ChangedByUser")
                        .WithMany("LeaseApplicationLogs")
                        .HasForeignKey("ChangedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseApplicationLog_User");

                    b.Navigation("Application");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseLog", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.User", "ChangedByUser")
                        .WithMany("LeaseLogs")
                        .HasForeignKey("ChangedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseLog_User");

                    b.HasOne("PropertyLeasing.API.Models.Lease", "Lease")
                        .WithMany("LeaseLogs")
                        .HasForeignKey("LeaseId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaseLog_Lease");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Log", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Log_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.User", "AssignedStaff")
                        .WithMany("MaintenanceRequestsAsStaff")
                        .HasForeignKey("AssignedStaffId")
                        .HasConstraintName("FK_MaintenanceRequest_Staff");

                    b.HasOne("PropertyLeasing.API.Models.User", "Tenant")
                        .WithMany("MaintenanceRequestsAsTenant")
                        .HasForeignKey("TenantUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceRequest_Tenant");

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceRequest_Unit");

                    b.Navigation("AssignedStaff");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceStatusHistory", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StatusHistory_MaintenanceRequest");

                    b.Navigation("MaintenanceRequest");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Notification", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.PaymentRecord", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Lease", "Lease")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentRecord_Lease");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Unit_Property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Navigation("LeaseLogs");

                    b.Navigation("PaymentRecords");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.LeaseApplication", b =>
                {
                    b.Navigation("ApplicationLogs");

                    b.Navigation("Documents");

                    b.Navigation("Leases");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("LeaseApplications");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Feedbacks");

                    b.Navigation("LeaseApplicationLogs");

                    b.Navigation("LeaseApplications");

                    b.Navigation("LeaseLogs");

                    b.Navigation("Logs");

                    b.Navigation("MaintenanceRequestsAsStaff");

                    b.Navigation("MaintenanceRequestsAsTenant");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
